[log]
level = "error"
output = "/var/log/realm.log"

[dns]
mode = "ipv4_only"
protocol = "tcp_and_udp"
nameservers = ["1.1.1.1:53", "1.0.0.1:53"]
min_ttl = 600
max_ttl = 3600
cache_size = 256

[[endpoints]]
listen = ":"
remote = ":40945"
remote_transport = "tls;sni="

[network]
no_tcp = false
use_udp = true
tcp_timeout = 5
udp_timeout = 30